version: "3.8"

networks:
  corp:
    driver: bridge

services:
  image-service:
    container_name: image-service
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/image-service/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: image-service:nx-dev
    ports:
      - 3333:3333
    environment:
      NODE_ENV: "development"
      PORT: 3333
    networks:
      - corp
    restart: on-failure

  wine-maker:
    container_name: wine-maker
    build:
      context: ./
      cache_from:
        - base-image:nx-base
      dockerfile: ./apps/wine-maker/Dockerfile
      args:
        NODE_ENV: "development"
        BUILD_FLAG: ""
    image: wine-maker:nx-dev
    ports:
      - 3334:3334
    environment:
      NODE_ENV: "development"
      PORT: 3334
    networks:
      - corp
    restart: on-failure
